import { Theme } from '.';


const colors = {
    white: "#FFF",
    white05: "rgba(255, 255, 255, 0.05)",
    white10: "rgba(255, 255, 255, 0.1)",
    white50: "rgba(255, 255, 255, 0.5)",
    white75: "rgba(255, 255, 255, 0.75)",
    white90: "rgba(255, 255, 255, 0.90)",
    black: "#000",
    black05: "rgba(0, 0, 0, 0.05)",
    black10: "rgba(0, 0, 0, 0.1)",
    black20: "rgba(0, 0, 0, 0.2)",
    black50: "rgba(0, 0, 0, 0.50)",
    black75: "rgba(0, 0, 0, 0.75)",
    black80: "rgba(0, 0, 0, 0.80)",
    black90: "rgba(0, 0, 0, 0.90)",
    github_black: "#24292f",
    vsc_black: "#1e1e1e",
    link: "#1f6286",
    important: "#e63672",
    warning: "#f08a24",
    danger: "#ff476f",
    plain: "#95afc0",
    marine: "#2BC2FF",
    blue: "#0288d1",
    red: "#c72e0f",
    orange: "#ff7043",
    purple: "#7e57c2",
    green: "#7cb342",
    yellow: "#fbc02d",
    light: "#f1f2f6",
    dark: "#252526",
    light_green: "#99bcac"
};

export const common = {
    ...colors,
    x: colors.light_green,
    xx: colors.green,
    xxx: colors.orange,
    xxxx: colors.link,
    xxxxx: colors.purple,
    wrong: colors.red,
    right: colors.green,
    danger: colors.danger,
    white: colors.white,
    black: colors.black,
    text_black: colors.black90,
    text_white: colors.white90,
    text_important: colors.red,
    text_link: colors.link,
    button: colors.blue,
    button_red: colors.red,
    button_default: colors.link,
    button_blue: colors.blue,
    button_orange: colors.orange,
    button_purple: colors.purple,
    button_green: colors.green,
    button_plain: colors.plain,
    important: colors.danger,
    pointer: colors.blue,
    header: colors.github_black,
    text_pointer: colors.plain,
    shadow: colors.black50,
}

export const light: Theme = {
    ...common,
    text: colors.black90,
    text_reverse: colors.white90,
    background: colors.white90,
    background_second: colors.light,
    main: colors.white75,
}

export const dark: Theme = {
    ...common,
    text: colors.white90,
    text_reverse: colors.black90,
    background: colors.black80,
    background_second: colors.dark,
    main: colors.vsc_black,
}